import type { Metadata } from "next";
import { Inter } from "next/font/google"
import ScrollToTop from "@/components/ui/ScrollToTop";
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-[var(--background)] text-[var(--foreground)] antialiased`}>
        {children}
        <ScrollToTop />
      </body>
    </html>
  )
}
